import type { Metadata } from "next";
import "@/ui/globals.css";
import { inter } from "@/ui/fonts";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "My Best Project - Generated by create next app ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body>{children}</body>
    </html>
  );
}
