// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
import { Customer } from "./definitions";

export const customers: Customer[] = [
  {
    _id: "cust-001",
    name: "John Smith",
    profile_photo: "/customers/favicon.ico",
    email: "john.smith001@gmail.com",
    password: "123456",
    phoneNumber: "0912345001",
    status: "Active",
  },
  {
    _id: "cust-002",
    name: "Emma Johnson",
    profile_photo: "/customers/favicon.ico",
    email: "emma.johnson002@gmail.com",
    password: "123456",
    phoneNumber: "0912345002",
    status: "Inactive",
  },
  {
    _id: "cust-003",
    name: "Michael Brown",
    profile_photo: "/customers/favicon.ico",
    email: "michael.brown003@gmail.com",
    password: "123456",
    phoneNumber: "0912345003",
    status: "Blocked",
  },
  {
    _id: "cust-004",
    name: "Sophia Davis",
    profile_photo: "/customers/favicon.ico",
    email: "sophia.davis004@gmail.com",
    password: "123456",
    phoneNumber: "0912345004",
    status: "Active",
  },
  {
    _id: "cust-005",
    name: "James Wilson",
    profile_photo: "/customers/favicon.ico",
    email: "james.wilson005@gmail.com",
    password: "123456",
    phoneNumber: "0912345005",
    status: "Inactive",
  },
  {
    _id: "cust-006",
    name: "Olivia Miller",
    profile_photo: "/customers/favicon.ico",
    email: "olivia.miller006@gmail.com",
    password: "123456",
    phoneNumber: "0912345006",
    status: "Active",
  },
  {
    _id: "cust-007",
    name: "William Moore",
    profile_photo: "/customers/favicon.ico",
    email: "william.moore007@gmail.com",
    password: "123456",
    phoneNumber: "0912345007",
    status: "Blocked",
  },
  {
    _id: "cust-008",
    name: "Ava Taylor",
    profile_photo: "/customers/favicon.ico",
    email: "ava.taylor008@gmail.com",
    password: "123456",
    phoneNumber: "0912345008",
    status: "Active",
  },
  {
    _id: "cust-009",
    name: "Benjamin Anderson",
    profile_photo: "/customers/favicon.ico",
    email: "benjamin.anderson009@gmail.com",
    password: "123456",
    phoneNumber: "0912345009",
    status: "Inactive",
  },
  {
    _id: "cust-010",
    name: "Charlotte Thomas",
    profile_photo: "/customers/favicon.ico",
    email: "charlotte.thomas010@gmail.com",
    password: "123456",
    phoneNumber: "0912345010",
    status: "Active",
  },

  // cust-011 to cust-050 follow the same pattern
];
